version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
  aws-ecs: circleci/aws-ecs@0.0.8

aliases:
  - &build-and-push-image
      aws-access-key-id: AWS_ACCESS_KEY_ID
      aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      account-url: AWS_ECR_ACCOUNT_URL
      repo: ${AWS_RESOURCE_NAME_PREFIX}
      region: AWS_DEFAULT_REGION
      tag: ${CIRCLE_SHA1}
      extra-build-args: "--build-arg BUILD_ACCOUNT_KIT_APP_SECRET=${ACCOUNT_KIT_APP_SECRET} --build-arg BUILD_AMPLITUDE_API_KEY=${AMPLITUDE_API_KEY} --build-arg BUILD_APOLLO_ENGINE=${APOLLO_ENGINE} --build-arg BUILD_FACEBOOK_APP_ID=${FACEBOOK_APP_ID} --build-arg BUILD_FACEBOOK_PAGES=${FACEBOOK_PAGES} --build-arg BUILD_FLAGR_URL=${FLAGR_URL} --build-arg BUILD_GOOGLE_ANALYTICS_TRACKING_ID=${GOOGLE_ANALYTICS_TRACKING_ID} --build-arg BUILD_GOOGLE_MAPS_KEY=${GOOGLE_MAPS_KEY} --build-arg BUILD_HOTJAR_SITE_ID=${HOTJAR_SITE_ID} --build-arg BUILD_IS_STAGING=${IS_STAGING} --build-arg BUILD_SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN} --build-arg BUILD_SENTRY_DSN=${SENTRY_DSN} --build-arg BUILD_SENTRY_ORG=${SENTRY_ORG} --build-arg BUILD_SENTRY_PROJECT=${SENTRY_PROJECT} --build-arg BUILD_WEBSERVICE_BASE_URL=${WEBSERVICE_BASE_URL}"
  - &deploy-service-update
      aws-region: ${AWS_DEFAULT_REGION}
      family: "${AWS_RESOURCE_NAME_PREFIX}-service"
      cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
      container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"

workflows:
  build-and-deploy-staging:
    jobs:
      - aws-ecr/build_and_push_image:
          context: frontend-staging
          <<: *build-and-push-image
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          context: frontend-staging
          <<: *deploy-service-update
          requires:
            - aws-ecr/build_and_push_image
  build-and-deploy-production:
    jobs:
      - deploy:
         type: approval
         requires:
            - aws-ecs/deploy-service-update
      - aws-ecr/build_and_push_image:
          context: frontend-production
          <<: *build-and-push-image
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          context: frontend-production
          <<: *deploy-service-update
          requires:
            - aws-ecr/build_and_push_image
